/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-like_border0': '&#xeda8;',
		'icon-like_border1': '&#xeda9;',
		'icon-check_availability': '&#xed94;',
		'icon-check_host': '&#xed9d;',
		'icon-fire': '&#xeda4;',
		'icon-arrow_right2': '&#xed92;',
		'icon-link': '&#xed93;',
		'icon-female': '&#xe900;',
		'icon-male': '&#xe909;',
		'icon-host': '&#xe913;',
		'icon-reminder': '&#xe915;',
		'icon-review': '&#xe917;',
		'icon-ticket': '&#xe919;',
		'icon-tour': '&#xe91b;',
		'icon-tour_cancelled': '&#xe91d;',
		'icon-activity_accomodation': '&#xe91f;',
		'icon-activity_experience': '&#xe923;',
		'icon-activity_restaurant': '&#xe925;',
		'icon-experience_not_found': '&#xe927;',
		'icon-find_buddy': '&#xe928;',
		'icon-find_buddy_stroke_white': '&#xe95b;',
		'icon-graphic_career': '&#xe98e;',
		'icon-graphic_collborative': '&#xe999;',
		'icon-graphic_cost': '&#xe9a5;',
		'icon-graphic_family': '&#xe9c8;',
		'icon-graphic_guarantee': '&#xe9dc;',
		'icon-graphic_host_community': '&#xe9ed;',
		'icon-graphic_host_price': '&#xe9f0;',
		'icon-graphic_local': '&#xe9f4;',
		'icon-graphic_schedule': '&#xea1b;',
		'icon-label_share': '&#xea1d;',
		'icon-order_success': '&#xea22;',
		'icon-route_map': '&#xea27;',
		'icon-travel_pack': '&#xea30;',
		'icon-travel_pack_stroke_white': '&#xea4f;',
		'icon-travel_story': '&#xea6e;',
		'icon-travel_story_stroke_white': '&#xea88;',
		'icon-trip_planner': '&#xeaa2;',
		'icon-trip_planner_stroke_white': '&#xeac9;',
		'icon-verify': '&#xeaf0;',
		'icon-all_tours0': '&#xeaf8;',
		'icon-all_tours1': '&#xeaf9;',
		'icon-bar0': '&#xeafa;',
		'icon-bar1': '&#xeafb;',
		'icon-culture0': '&#xeafc;',
		'icon-culture1': '&#xeafd;',
		'icon-food0': '&#xeafe;',
		'icon-food1': '&#xeaff;',
		'icon-others0': '&#xeb00;',
		'icon-others1': '&#xeb01;',
		'icon-outdoor0': '&#xeb02;',
		'icon-outdoor1': '&#xeb03;',
		'icon-workshop0': '&#xeb04;',
		'icon-workshop1': '&#xeb05;',
		'icon-copy': '&#xeb06;',
		'icon-email': '&#xeb0b;',
		'icon-facebook': '&#xeb0c;',
		'icon-linkedin': '&#xeb0e;',
		'icon-twitter': '&#xeb10;',
		'icon-saved': '&#xeb12;',
		'icon-saved_thin': '&#xeb13;',
		'icon-saved_white': '&#xeb14;',
		'icon-ticket1': '&#xeb15;',
		'icon-ticket_white': '&#xeb16;',
		'icon-china': '&#xeb17;',
		'icon-usa': '&#xeb1e;',
		'icon-circle_decrease': '&#xeb25;',
		'icon-circle_increase': '&#xeb27;',
		'icon-change_password0': '&#xeb29;',
		'icon-change_password1': '&#xeb32;',
		'icon-invite0': '&#xeb3b;',
		'icon-invite1': '&#xeb50;',
		'icon-payment0': '&#xeb65;',
		'icon-payment1': '&#xeb72;',
		'icon-personal_info0': '&#xeb7f;',
		'icon-personal_info1': '&#xeb89;',
		'icon-profile0': '&#xeb93;',
		'icon-profile1': '&#xec0f;',
		'icon-saved0': '&#xec8b;',
		'icon-saved1': '&#xec93;',
		'icon-ticket0': '&#xec9b;',
		'icon-ticket11': '&#xecab;',
		'icon-travel_story0': '&#xecbb;',
		'icon-travel_story1': '&#xecc9;',
		'icon-trip_planner0': '&#xecd7;',
		'icon-trip_planner1': '&#xece8;',
		'icon-accomodation': '&#xecf9;',
		'icon-action_back': '&#xecfa;',
		'icon-add': '&#xecfb;',
		'icon-add_photo': '&#xecfc;',
		'icon-arrow_down': '&#xecfd;',
		'icon-arrow_left0': '&#xecfe;',
		'icon-arrow_right0': '&#xecff;',
		'icon-arrow_right1': '&#xed00;',
		'icon-attachment': '&#xed01;',
		'icon-attachment0': '&#xed02;',
		'icon-bad': '&#xed03;',
		'icon-bike': '&#xed04;',
		'icon-blocked_date': '&#xed06;',
		'icon-calendar': '&#xed07;',
		'icon-cancel': '&#xed08;',
		'icon-car': '&#xed09;',
		'icon-change': '&#xed0b;',
		'icon-check0': '&#xed0c;',
		'icon-check1': '&#xed0d;',
		'icon-check4': '&#xed0e;',
		'icon-check_selected': '&#xed0f;',
		'icon-close': '&#xed10;',
		'icon-close1': '&#xed11;',
		'icon-close2': '&#xed12;',
		'icon-close3': '&#xed13;',
		'icon-close4': '&#xed14;',
		'icon-comment': '&#xed15;',
		'icon-decrease': '&#xed16;',
		'icon-decrease1': '&#xed17;',
		'icon-delete': '&#xed18;',
		'icon-dropdown': '&#xed1a;',
		'icon-dropdown_white': '&#xed1b;',
		'icon-edit1': '&#xed1c;',
		'icon-experience': '&#xed1d;',
		'icon-export_csv': '&#xed1e;',
		'icon-good': '&#xed1f;',
		'icon-heart0': '&#xed20;',
		'icon-heart1': '&#xed21;',
		'icon-heart2': '&#xed22;',
		'icon-help0': '&#xed23;',
		'icon-help1': '&#xed24;',
		'icon-host1': '&#xed25;',
		'icon-inbox': '&#xed26;',
		'icon-inbox0': '&#xed27;',
		'icon-inbox1': '&#xed28;',
		'icon-include': '&#xed29;',
		'icon-increase': '&#xed2a;',
		'icon-increase1': '&#xed2b;',
		'icon-info': '&#xed2c;',
		'icon-invite_friend': '&#xed2e;',
		'icon-joined0': '&#xed2f;',
		'icon-joined1': '&#xed30;',
		'icon-Label-Icon-Location': '&#xed31;',
		'icon-language0': '&#xed32;',
		'icon-language1': '&#xed33;',
		'icon-like': '&#xed34;',
		'icon-location': '&#xed35;',
		'icon-location0': '&#xed36;',
		'icon-location1': '&#xed37;',
		'icon-lock': '&#xed38;',
		'icon-lock-lg': '&#xed39;',
		'icon-logout': '&#xed3a;',
		'icon-message': '&#xed3b;',
		'icon-move': '&#xed3c;',
		'icon-password_hide': '&#xed3d;',
		'icon-password_show': '&#xed3e;',
		'icon-phone': '&#xed3f;',
		'icon-picture': '&#xed40;',
		'icon-preview': '&#xed41;',
		'icon-price': '&#xed42;',
		'icon-print': '&#xed43;',
		'icon-publish': '&#xed44;',
		'icon-refund0': '&#xed45;',
		'icon-refund1': '&#xed46;',
		'icon-restaurant': '&#xed47;',
		'icon-reviews': '&#xed48;',
		'icon-save': '&#xed51;',
		'icon-search0': '&#xed52;',
		'icon-search1': '&#xed53;',
		'icon-secure': '&#xed54;',
		'icon-share': '&#xed55;',
		'icon-share_report': '&#xed56;',
		'icon-star_color': '&#xed57;',
		'icon-star_gray': '&#xed58;',
		'icon-star_stroke': '&#xed59;',
		'icon-star_white': '&#xed5a;',
		'icon-star_yellow': '&#xed5b;',
		'icon-tickets': '&#xed5c;',
		'icon-time0': '&#xed5d;',
		'icon-time1': '&#xed5e;',
		'icon-tours': '&#xed5f;',
		'icon-train': '&#xed6f;',
		'icon-travel_pack1': '&#xed71;',
		'icon-travel_story2': '&#xed72;',
		'icon-trip0': '&#xed73;',
		'icon-trip1': '&#xed74;',
		'icon-trip_planner2': '&#xed75;',
		'icon-type': '&#xed76;',
		'icon-upload': '&#xed77;',
		'icon-user': '&#xed78;',
		'icon-user0': '&#xed79;',
		'icon-user1': '&#xed7a;',
		'icon-user2': '&#xed7b;',
		'icon-verified_badge': '&#xed7c;',
		'icon-views': '&#xed8a;',
		'icon-walk': '&#xed8b;',
		'icon-warning0': '&#xed8d;',
		'icon-Web-Icon-Download': '&#xed8e;',
		'icon-withdraw': '&#xed8f;',
		'icon-work': '&#xed90;',
		'icon-wrong': '&#xed91;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
